services:
    behat_coverage_extension.remote_code_coverage_listener:
        class: \BehatCoverageExtension\RemoteCodeCoverageListener
        arguments:
            - '@mink'
            - '%behat_coverage_extension.phpunit_xml_path%'
            - '%behat_coverage_extension.coverage_target_directory%'
        tags:
            - { name: event_dispatcher.subscriber }

    behat_coverage_extension.local_code_coverage_listener:
        class: BehatCoverageExtension\LocalCodeCoverageListener
        arguments:
            - '%behat_coverage_extension.phpunit_xml_path%'
            - '%behat_coverage_extension.coverage_target_directory%'
        tags:
            - { name: event_dispatcher.subscriber }
